import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FungiDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          FungiDB- A Databse for Fungi.
        </h1>

        <p className={styles.description}>
          description here
        </p>

        <div className={styles.grid}>
          <Link href="/nucleotideBlast">
            <a className={styles.card}>
              <h2>Nucleotide Blast &rarr;</h2>
              <p>Some description here</p>
            </a>
          </Link>

          <Link href="/blastx">
            <a className={styles.card}>
              <h2>Blastx &rarr;</h2>
              <p>Some description here</p>
            </a>
          </Link>

          <Link href="/tblastn">
            <a className={styles.card}>
              <h2>TBlastn &rarr;</h2>
              <p>Some description here</p>
            </a>
          </Link>

          <Link href="/proteinBlast">
            <a className={styles.card}>
              <h2>Protein Blast &rarr;</h2>
              <p>Some description here</p>
            </a>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        <h4>
          Created by: Haihua Wang and Simon Cole at the <a className="footerLink" href="https://sunnymicrobiome.weebly.com">Sunny Liao Lab</a>
        </h4>
      </footer>
    </div>
  )
}
